### ISSUE TITLE
[Bug-发哥]注册：普通用户注册的一些不应该注册成功的例子

### ISSUE THREAD

**Issue by SheerLin** [PM-XingYi/XingYi#18]
1. 照理来说，所有的field都不能为空，任何一个为空都不能注册成功
2. 邮箱：虽然界面上有提示要输入@,但是如果我不输入，照样可以注册成功 
   3.手机那一栏，应该只允许输入数字。

**Comment by fxiangyi** [comment]
@chyt123

**Comment by wangzhizhen** [comment]
fixed.
