### ISSUE TITLE
注册时不显示条款

### ISSUE THREAD

**Issue by hermione521** [PM-XingYi/XingYi#2]
需要条款

**Comment by hermione521** [comment]
1. 用户注册成功后，行益网将给予每个用户一个用户帐号及相应的密码，该用户帐号和密码由用户负责保管；用户应当对以其用户帐号进行的所有活动和事件负法律责任。
2. 用户须对在行益网的注册信息的真实性、合法性、有效性承担全部责任，用户不得冒充他人；不得利用他人的名义发布任何信息；不得恶意使用注册帐户导致其他用户误认；否则行益网有权立即停止提供服务，收回其帐号并由用户独自承担由此而产生的一切法律责任。
3. 用户直接或通过各类方式（如 RSS 源和站外 API 引用等）间接使用行益网服务和数据的行为，都将被视作已无条件接受本协议全部内容；若用户对本协议的任何条款存在异议，请停止使用行益网所提供的全部服务。
4. 行益网是一个信息分享、传播及获取的平台，用户通过行益网发表的「公开」信息为公开的信息，其他第三方均可以通过行益网获取用户发表的信息，用户对任何信息的发表即认可该信息为公开的信息，并单独对此行为承担法律责任；用户通过行益网发表的「隐私」信息为不公开的信息，其他用户没有权利获取这些隐私信息；任何用户不愿被其他第三人获知的信息都不应该在行益网上进行发表。
5. 用户承诺不得以任何方式利用行益网直接或间接从事违反中国法律、以及社会公德的行为，行益网有权对违反上述承诺的内容予以删除。
6. 用户不得利用行益网服务制作、上载、复制、发布、传播或者转载如下内容：
   - 反对宪法所确定的基本原则的；
   - 危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；
   - 损害国家荣誉和利益的；
   - 煽动民族仇恨、民族歧视，破坏民族团结的；
   - 破坏国家宗教政策，宣扬邪教和封建迷信的；
   - 散布谣言，扰乱社会秩序，破坏社会稳定的；
7. 行益网有权对用户使用行益网的情况进行审查和监督，如用户在使用行益网时违反任何上述规定，行益网或其授权的人有权要求用户改正或直接采取一切必要的措施（包括但不限于更改或删除用户张贴的内容、暂停或终止用户使用行益网的权利）以减轻用户不当行为造成的影响。

**Comment by fxiangyi** [comment]
@chyt123
