### ISSUE TITLE
[Bug-干姐姐]搜索结果-返回条数没有正确显示

### ISSUE THREAD

**Issue by SheerLin** [PM-XingYi/XingYi#23]
步骤:在搜索框输入“pj”，点放大镜图标；预期：界面上显示“找到X条符合搜索条件blablbla的结果”；实际：没有显示具体的条数，即“找到条符合“pj”搜索条件的项目”

**Comment by hermione521** [comment]
@SheerLin fixed. Pls check

**Comment by SheerLin** [comment]
Retest:pass
